services:
  server:
    build: ../
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/results:/app/results
    depends_on:
      - mongodb://mongodb:27017/ai-planner

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: